# Generated by Django 5.1.6 on 2025-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=50)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('problemas_medicos', models.TextField(blank=True, null=True)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
