# Generated by Django 5.1.6 on 2025-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_sensordata_estado_puerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='estado_puerta',
            field=models.CharField(max_length=20),
        ),
    ]
